### ISSUE TITLE
Types for TypeScript project

### ISSUE THREAD

**Issue by renaco** [bqworks/slider-pro-js#1]
Hi there, 

I really appreciate the library is awesome. Only that when I started to implement on my TypeScript project I found this issue:

```
Could not find a declaration file for module 'slider-pro-js'. '/my-ts-project/node_modules/slider-pro-js/entry/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/slider-pro-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'slider-pro-js';
 ``` 
 
 When I try to install that types appears this message:
 
 ```bash
➜   npm install @types/slider-pro-js
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fslider-pro-js - Not found
npm ERR! 404
npm ERR! 404  '@types/slider-pro-js@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/my-user/.npm/_logs/2023-01-09T17_12_53_907Z-debug-0.log 
 ```

It looks like types is unavailable.
I will wait for your answer. Thanks in advance!

**Comment by davidghi** [comment]
Hi,

This could be due to using JavaScript (this slider is written in plain JavaScript) in a TypeScript project. Please check some possible solutions here: https://stackoverflow.com/questions/38318542/how-to-use-javascript-in-typescript
